# Generated by Django 3.1.6 on 2021-04-29 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 29, 1, 31, 33, 261739)),
        ),
    ]
