# Generated by Django 3.1.6 on 2021-04-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=300)),
                ('assignment_description', models.CharField(max_length=1500)),
                ('assignment_points', models.IntegerField()),
                ('assignment_code', models.CharField(max_length=1000)),
                ('assignment_test_cases', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=300)),
                ('classroom_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='thesql.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='thesql.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentGrade',
            fields=[
                ('assignment_grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('points_earned', models.IntegerField()),
                ('points_total', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='thesql.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='thesql.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='thesql.classroom'),
        ),
    ]
