# Generated by Django 3.1.6 on 2021-04-29 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thesql', '0002_assignment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CRN', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=100)),
                ('Instructor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('NetId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('NetId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CRN', models.IntegerField()),
                ('Credits', models.IntegerField()),
                ('Score', models.FloatField()),
            ],
            options={
                'db_table': 'Enrollments',
                'unique_together': {('NetId', 'CRN')},
            },
        ),
    ]
